kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-dev
  namespace: dev-nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-block-gold
  volumeMode: Filesystem
