kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dev-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: dev.my.org/nfs
reclaimPolicy: Delete
mountOptions:
  - vers=4.1
volumeBindingMode: Immediate
